validators: # note that we're deprecating the `validator` top level field and converting it to an array.
  - name: alice
    bonded: 1000stake # note that we're renaming `staked` as `bonded`.

    # we're now deprecating the `host` field from the top level,
    # and directly using 'app' and 'config' fields to configure addresses.

    # `validators[].app` was `init.app` before and moved under validator info.
    # yml representation of ~/.marsd/config/app.toml
    app:
      grpc:
        address: ""
      grpc-web:
        address: ""
      api:
        address: ""
        
    # validators[].config was `init.config` before and moved under validator info.
    # yml representation of ~/.marsd/config/config.toml
    config: 
      rpc:
        laddr: ""
      p2p:
        laddr: ""
      pprof_laddr: ""

    # validators[].client was `init.client` before and moved under validator info.
    # yml representation of ~/.marsd/config/client.toml
    client: 

    # 'gentx' is a new field to introduce under the validator info,
    # when this is provided we should use it to overwrite defaults while creating a gentx.
    # we need to create a struct for gentx.
    gentx:
      amount: 1000stake # this should overwrite if `validators[].bonded` was also set.
      moniker: mymoniker # if this isn't provided we can default to `moniker-alice`,
                        # `alice` stands for whatever the name of the validator is: `validators[].name`
      commission-max-change-rate:
      # ... and other fields needed. Run 'marsd gentx -h' and
      # check the Example section in the printed docs to see all available configuration

  - name: bob
    bonded: 500stake
