init:
  home: "./defund"
build:
  main: "./app"
accounts:
  - name: alice
    coins: ["2000000000000000ugrid"]
    mnemonic: "alley afraid soup fall idea toss can goose become valve initial strong forward bright dish figure check leopard decide warfare hub unusual join cart"
  - name: bob
    coins: ["100000000000000000ugrid"]
    mnemonic: "alpha crisp zoo letter pepper subway crew drum illegal powder input shuffle team east village nurse captain mule token ice drive act boy punch"
  - name: faucet
    coins: ["50000000000000ugrid",]
    mnemonic: "bomb choose medal limb place hip axis pave reject rack recipe cover family vivid humble kingdom exhibit limit snow biology special swing emotion call"
validator:
  name: alice
  staked: "100000000ugrid"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins: ["50000000000000ugrid"]
genesis:
  chain_id: "gridtestnet-1000"
  app_state:
    staking:
      params:
        bond_denom: "ugrid"
    mint:
      params:
        mint_denom: "ugrid"
    crisis:
      constant_fee:
        denom: "ugrid"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "ugrid"
    broker:
      brokers:
    minimum-gas-prices: "0.0000025ugrid"